# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: winrun2


    steps:
    - uses: actions/checkout@v2

    - name: Set up Maven
      uses: pabsi/setup-maven@v4
      with:
        maven-version: 3.5.4

    - name: Build with Maven
      run: mvn -B clean install

      
  
    
